name: Abode Camera Streamer
version: 1.0.2
description: Provides streaming video from Abode security cameras
url: https://github.com/tradel/abode2rtc
image: "docker.io/tradel/addon-{arch}-abode2rtc"
arch: [amd64]

slug: abode2rtc
init: false
startup: services
host_network: true
homeassistant_api: true
video: true
audio: true
ingress: true

ingress_port: 1984
panel_icon: mdi:camera-wireless
map: ["config:ro"]

ports:
  1984/tcp: 1984
  8554/tcp: 8554
  8555/tcp: 8555
  8555/udp: 8555

schema:
  abode_username: str
  abode_password: str
  locale: str

options:
  abode_username: ""
  abode_password: ""
  locale: "en-US"